// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDbkW38RLizbwqwi_DCoPSgOlRrD98-0',
    appId: '1:960994054856:web:2dc2b15eab4415a0ea4bfd',
    messagingSenderId: '960994054856',
    projectId: 'fooddeliveryapp-d4c54',
    authDomain: 'fooddeliveryapp-d4c54.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-d4c54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0asMkUIVwyfEYvxNIpdKTQ4THUOhByI',
    appId: '1:960994054856:android:893e269a5cc660c5ea4bfd',
    messagingSenderId: '960994054856',
    projectId: 'fooddeliveryapp-d4c54',
    storageBucket: 'fooddeliveryapp-d4c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKjGZp9BNSPVuuA18a7fahsJ5RkhcpO0',
    appId: '1:960994054856:ios:7dcaacf8e18f26d5ea4bfd',
    messagingSenderId: '960994054856',
    projectId: 'fooddeliveryapp-d4c54',
    storageBucket: 'fooddeliveryapp-d4c54.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKjGZp9BNSPVuuA18a7fahsJ5RkhcpO0',
    appId: '1:960994054856:ios:7dcaacf8e18f26d5ea4bfd',
    messagingSenderId: '960994054856',
    projectId: 'fooddeliveryapp-d4c54',
    storageBucket: 'fooddeliveryapp-d4c54.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnDbkW38RLizbwqwi_DCoPSgOlRrD98-0',
    appId: '1:960994054856:web:2e4a198a08378122ea4bfd',
    messagingSenderId: '960994054856',
    projectId: 'fooddeliveryapp-d4c54',
    authDomain: 'fooddeliveryapp-d4c54.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-d4c54.firebasestorage.app',
  );
}
